### ISSUE TITLE
Gradle fails with latest version

### ISSUE THREAD

**Issue by NarzaryU** [soeminnminn/EngMyanDictionary#1]
Gradle build fails after upgrading 
buildscript {
    ext.kotlin_version = '1.3.71'
    repositories {
        google()
        jcenter()
        
    }

to 

 buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        jcenter()
        
    }

**Comment by soeminnminn** [comment]
Why do you need for upgrading? 
As upon you.
